# Generated by Django 4.0.2 on 2022-02-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasApp', '0002_habitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
